export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const SUJETO_CON_VERBO = 'SUJETO_CON_VERBO';
export const VERBO_CON_COMPLEMENTO = 'VERBO_CON_COMPLEMENTO';
export const CHECK_IF_CORRECT = 'CHECK_IF_CORRECT';
export const CLEAN_STATE = 'CLEAN_STATE';
export const PREDEFINED_VERB = 'PREDEFINED_VERB';
export const HANDLE_SPECIAL_CHAR_CLICK = 'HANDLE_SPECIAL_CHAR_CLICK';
